select  LONGITUDE,
        LATITUDE,
        LOCATION,
        PROVINCE,
        LOCATION_LEVEL,
        AVG(TOTAL_RECOVERED) as AVG_TOTAL_RECOVERED
        AVG(TOTAL_DEATHS) as AVG_TOTAL_DEATHS 
        AVG(TOTAL_ACTIVE_CASES) as AVG_TOTAL_ACTIVE_CASES
        AVG(TOTAL_CASES) as AVG_TOTAL_CASES 
    from FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS."COVID_19_INDONESIA_HARSIMAR_SINGH"